import re

# Mapping of lowercase city keywords to (Standard City Name, Standard State Name)
CITIES_MAP = {
    # Delhi NCR
    'delhi': ('New Delhi', 'Delhi'),
    'new delhi': ('New Delhi', 'Delhi'),
    'janakpuri': ('New Delhi', 'Delhi'),
    'vikaspuri': ('New Delhi', 'Delhi'),
    'dwarka': ('New Delhi', 'Delhi'),
    'rohini': ('New Delhi', 'Delhi'),
    'pitampura': ('New Delhi', 'Delhi'),
    'paschim vihar': ('New Delhi', 'Delhi'),
    'shalimar bagh': ('New Delhi', 'Delhi'),
    'punjabi bagh': ('New Delhi', 'Delhi'),
    'vasant kunj': ('New Delhi', 'Delhi'),
    'ashok vihar': ('New Delhi', 'Delhi'),
    'narela': ('New Delhi', 'Delhi'),
    'burari': ('New Delhi', 'Delhi'),
    'mausam vihar': ('New Delhi', 'Delhi'),
    'sreshtha vihar': ('New Delhi', 'Delhi'),
    'dayanand vihar': ('New Delhi', 'Delhi'),
    'kailash hills': ('New Delhi', 'Delhi'),
    'east of kailash': ('New Delhi', 'Delhi'),
    'model town': ('New Delhi', 'Delhi'),
    'jasola': ('New Delhi', 'Delhi'),
    'saraswati vihar': ('New Delhi', 'Delhi'),
    'vaisakha enclave': ('New Delhi', 'Delhi'),
    'mianwali nagar': ('New Delhi', 'Delhi'),
    'shakti nagar': ('New Delhi', 'Delhi'),
    'alipur': ('New Delhi', 'Delhi'),
    'nangloi': ('New Delhi', 'Delhi'),
    'hastsal': ('New Delhi', 'Delhi'),
    'ranhaulla': ('New Delhi', 'Delhi'),
    'timarpur': ('New Delhi', 'Delhi'),
    'uttam nagar': ('New Delhi', 'Delhi'),
    'kirti nagar': ('New Delhi', 'Delhi'),
    'meera bagh': ('New Delhi', 'Delhi'),
    'rajouri garden': ('New Delhi', 'Delhi'),
    'daryaganj': ('New Delhi', 'Delhi'),
    'mayapuri': ('New Delhi', 'Delhi'),
    'karol bagh': ('New Delhi', 'Delhi'),
    'karolbagh': ('New Delhi', 'Delhi'),
    'hari nagar': ('New Delhi', 'Delhi'),
    'jhandewalan': ('New Delhi', 'Delhi'),
    'najafgarh': ('New Delhi', 'Delhi'),
    'nihal vihar': ('New Delhi', 'Delhi'),
    'samepur': ('New Delhi', 'Delhi'),
    'kingsway camp': ('New Delhi', 'Delhi'),
    'ranjeet nagar': ('New Delhi', 'Delhi'),
    'keshav puram': ('New Delhi', 'Delhi'),
    'keshavpuram': ('New Delhi', 'Delhi'),
    'darya ganj': ('New Delhi', 'Delhi'),
    'chander nagar': ('New Delhi', 'Delhi'),
    'g t b nagar': ('New Delhi', 'Delhi'),
    'gtb nagar': ('New Delhi', 'Delhi'),
    'mansarover garden': ('New Delhi', 'Delhi'),
    'nilothi': ('New Delhi', 'Delhi'),
    'tajpur khurd': ('New Delhi', 'Delhi'),
    'shahbad daulatpur': ('New Delhi', 'Delhi'),
    'ladpur': ('New Delhi', 'Delhi'),
    'prashant vihar': ('New Delhi', 'Delhi'),
    'bakhtawarpur': ('New Delhi', 'Delhi'),
    'khera kalan': ('New Delhi', 'Delhi'),
    'shastri nagar': ('New Delhi', 'Delhi'),
    'siraspur': ('New Delhi', 'Delhi'),
    'azadpur': ('New Delhi', 'Delhi'),
    'holambi khurd': ('New Delhi', 'Delhi'),
    'nanak piao': ('New Delhi', 'Delhi'),
    'palla mazra': ('New Delhi', 'Delhi'),
    'pooth kalan': ('New Delhi', 'Delhi'),
    'qutabgarh': ('New Delhi', 'Delhi'),
    'libaspur': ('New Delhi', 'Delhi'),
    'wazirpur': ('New Delhi', 'Delhi'),
    'gole market': ('New Delhi', 'Delhi'),
    
    # Uttar Pradesh
    'noida': ('Noida', 'Uttar Pradesh'),
    'greater noida': ('Greater Noida', 'Uttar Pradesh'),
    'gr noida': ('Greater Noida', 'Uttar Pradesh'),
    'gn': ('Greater Noida', 'Uttar Pradesh'),
    'ghaziabad': ('Ghaziabad', 'Uttar Pradesh'),
    'gzb': ('Ghaziabad', 'Uttar Pradesh'),
    'indirapuram': ('Indirapuram', 'Uttar Pradesh'),
    'ind': ('Indirapuram', 'Uttar Pradesh'),
    'brij vihar': ('Indirapuram', 'Uttar Pradesh'),
    'rajinder nagar': ('New Delhi', 'Delhi'), 
    'rajajipuram': ('Lucknow', 'Uttar Pradesh'),
    'kavi nagar': ('Ghaziabad', 'Uttar Pradesh'),
    'karl huber': ('Noida', 'Uttar Pradesh'),
    'salvation tree': ('Greater Noida', 'Uttar Pradesh'),
    'bhai joga singh': ('New Delhi', 'Delhi'),
    'anglo arabic': ('New Delhi', 'Delhi'),
    'meerut': ('Meerut', 'Uttar Pradesh'),
    'modipuram': ('Meerut', 'Uttar Pradesh'),
    'partapur': ('Meerut', 'Uttar Pradesh'),
    'mawana': ('Meerut', 'Uttar Pradesh'),
    'agra': ('Agra', 'Uttar Pradesh'),
    'sikandra': ('Agra', 'Uttar Pradesh'),
    'dayalbagh': ('Agra', 'Uttar Pradesh'),
    'etmadpur': ('Agra', 'Uttar Pradesh'),
    'fatehabad': ('Agra', 'Uttar Pradesh'),
    'runakata': ('Agra', 'Uttar Pradesh'),
    'kiraoli': ('Agra', 'Uttar Pradesh'),
    'chhota': ('Agra', 'Uttar Pradesh'),
    'chata': ('Agra', 'Uttar Pradesh'),
    'chhata': ('Agra', 'Uttar Pradesh'),
    'mathura': ('Mathura', 'Uttar Pradesh'),
    'vrindavan': ('Mathura', 'Uttar Pradesh'),
    'vrindaban': ('Mathura', 'Uttar Pradesh'),
    'kosikalan': ('Mathura', 'Uttar Pradesh'),
    'kosi kalan': ('Mathura', 'Uttar Pradesh'),
    'barsana': ('Mathura', 'Uttar Pradesh'),
    'chhata mathura': ('Mathura', 'Uttar Pradesh'),
    'chata mathura': ('Mathura', 'Uttar Pradesh'),
    'farah': ('Mathura', 'Uttar Pradesh'),
    'gobardhan': ('Mathura', 'Uttar Pradesh'),
    'goverdhan': ('Mathura', 'Uttar Pradesh'),
    'raya': ('Mathura', 'Uttar Pradesh'),
    'mauja govndpr': ('Mathura', 'Uttar Pradesh'),
    'mauja govndpr mathura': ('Mathura', 'Uttar Pradesh'),
    'naujheel': ('Mathura', 'Uttar Pradesh'),
    'mahavan': ('Mathura', 'Uttar Pradesh'),
    'sadabad': ('Mathura', 'Uttar Pradesh'),
    'kanpur': ('Kanpur', 'Uttar Pradesh'),
    'lucknow': ('Lucknow', 'Uttar Pradesh'),
    'varanasi': ('Varanasi', 'Uttar Pradesh'),
    'banaras': ('Varanasi', 'Uttar Pradesh'),
    'bijnor': ('Bijnor', 'Uttar Pradesh'),
    'saharanpur': ('Saharanpur', 'Uttar Pradesh'),
    'muzaffarnagar': ('Muzaffarnagar', 'Uttar Pradesh'),
    'muzzafar nagar': ('Muzaffarnagar', 'Uttar Pradesh'),
    'hapur': ('Hapur', 'Uttar Pradesh'),
    'baghpat': ('Baghpat', 'Uttar Pradesh'),
    'auraiya': ('Auraiya', 'Uttar Pradesh'),
    'sonebhadra': ('Sonebhadra', 'Uttar Pradesh'),
    'obra': ('Sonebhadra', 'Uttar Pradesh'),
    'robertsganj': ('Sonebhadra', 'Uttar Pradesh'),
    'pipri': ('Sonebhadra', 'Uttar Pradesh'),
    'bareilly': ('Bareilly', 'Uttar Pradesh'),
    'shamli': ('Shamli', 'Uttar Pradesh'),
    'pratapgarh': ('Pratapgarh', 'Uttar Pradesh'),
    'orai': ('Orai', 'Uttar Pradesh'),
    'lakhimpur': ('Lakhimpur Kheri', 'Uttar Pradesh'),
    'fatehpur': ('Fatehpur', 'Uttar Pradesh'),
    'barabanki': ('Barabanki', 'Uttar Pradesh'),
    'padrauna': ('Padrauna', 'Uttar Pradesh'),
    'gorakhpur': ('Gorakhpur', 'Uttar Pradesh'),
    'dadri': ('Dadri', 'Uttar Pradesh'),
    'pilibhit': ('Pilibhit', 'Uttar Pradesh'),
    'sitapur': ('Sitapur', 'Uttar Pradesh'),
    'kashipur': ('Kashipur', 'Uttarakhand'), 
    'hastinapur': ('Hastinapur', 'Uttar Pradesh'),
    'naukuchiatal': ('Naukuchiatal', 'Uttarakhand'),
    'ranikhet': ('Ranikhet', 'Uttarakhand'),
    'roorkee': ('Roorkee', 'Uttarakhand'),
    
    # Haryana
    'gurugram': ('Gurugram', 'Haryana'),
    'gurgaon': ('Gurugram', 'Haryana'),
    'ggn': ('Gurugram', 'Haryana'),
    'faridabad': ('Faridabad', 'Haryana'),
    'ambala': ('Ambala', 'Haryana'),
    'sirsa': ('Sirsa', 'Haryana'),
    'kurukshetra': ('Kurukshetra', 'Haryana'),
    'fatehabad': ('Fatehabad', 'Haryana'),
    'karnal': ('Karnal', 'Haryana'),
    'nuh': ('Nuh', 'Haryana'),
    'palwal': ('Palwal', 'Haryana'),
    'bhiwani': ('Bhiwani', 'Haryana'),
    'sonipat': ('Sonipat', 'Haryana'),
    'sonepat': ('Sonipat', 'Haryana'),
    'jind': ('Jind', 'Haryana'),
    'jhajjar': ('Jhajjar', 'Haryana'),
    'panchkula': ('Panchkula', 'Haryana'),
    'rewari': ('Rewari', 'Haryana'),
    'hisar': ('Hisar', 'Haryana'),
    'hissar': ('Hisar', 'Haryana'),
    'kaithal': ('Kaithal', 'Haryana'),
    'yamunanagar': ('Yamunanagar', 'Haryana'),
    'yamuna nagar': ('Yamunanagar', 'Haryana'),
    'ballabgarh': ('Ballabgarh', 'Haryana'),
    'bahadurgarh': ('Bahadurgarh', 'Haryana'),
    'rohtak': ('Rohtak', 'Haryana'),
    'panipat': ('Panipat', 'Haryana'),
    'nilokheri': ('Nilokheri', 'Haryana'),
    'assandh': ('Karnal', 'Haryana'),
    'gadaur': ('Sonepat', 'Haryana'),
    'narnaul': ('Narnaul', 'Haryana'),
    'panori': ('Udaipur', 'Rajasthan'),
    
    # Punjab
    'ludhiana': ('Ludhiana', 'Punjab'),
    'ldh': ('Ludhiana', 'Punjab'),
    'amritsar': ('Amritsar', 'Punjab'),
    'jalandhar': ('Jalandhar', 'Punjab'),
    'patiala': ('Patiala', 'Punjab'),
    'bathinda': ('Bathinda', 'Punjab'),
    'mohali': ('Mohali', 'Punjab'),
    'pathankot': ('Pathankot', 'Punjab'),
    'moga': ('Moga', 'Punjab'),
    'phagwara': ('Phagwara', 'Punjab'),
    'sangrur': ('Sangrur', 'Punjab'),
    'ropar': ('Ropar', 'Punjab'),
    'firozpur': ('Firozpur', 'Punjab'),
    'khanna': ('Khanna', 'Punjab'),
    'barnala': ('Barnala', 'Punjab'),
    'sidhwan': ('Ludhiana', 'Punjab'),
    'nakodar': ('Jalandhar', 'Punjab'),
    'kartarpur': ('Jalandhar', 'Punjab'),
    'goraya': ('Jalandhar', 'Punjab'),
    'adampur': ('Jalandhar', 'Punjab'),
    'shahkot': ('Jalandhar', 'Punjab'),
    'samrala': ('Ludhiana', 'Punjab'),
    
    # Rajasthan
    'jaipur': ('Jaipur', 'Rajasthan'),
    'jodhpur': ('Jodhpur', 'Rajasthan'),
    'udaipur': ('Udaipur', 'Rajasthan'),
    'kota': ('Kota', 'Rajasthan'),
    'ajmer': ('Ajmer', 'Rajasthan'),
    'bikaner': ('Bikaner', 'Rajasthan'),
    'alwar': ('Alwar', 'Rajasthan'),
    'sri ganganagar': ('Sri Ganganagar', 'Rajasthan'),
    'pilani': ('Pilani', 'Rajasthan'),
    'jhalawar': ('Jhalawar', 'Rajasthan'),
    'bundi': ('Bundi', 'Rajasthan'),
    'nasirabad': ('Ajmer', 'Rajasthan'),
    
    # Uttarakhand
    'dehradun': ('Dehradun', 'Uttarakhand'),
    'haridwar': ('Haridwar', 'Uttarakhand'),
    'hardwar': ('Haridwar', 'Uttarakhand'),
    'mussoorie': ('Mussoorie', 'Uttarakhand'),
    'haldwani': ('Haldwani', 'Uttarakhand'),
    'kotdwar': ('Kotdwar', 'Uttarakhand'),
    'rishikesh': ('Rishikesh', 'Uttarakhand'),
    'selakui': ('Dehradun', 'Uttarakhand'),
    
    # Himachal Pradesh
    'shimla': ('Shimla', 'Himachal Pradesh'),
    'mandi': ('Mandi', 'Himachal Pradesh'),
    'solan': ('Solan', 'Himachal Pradesh'),
    'chamba': ('Chamba', 'Himachal Pradesh'),
    'hamirpur': ('Hamirpur', 'Himachal Pradesh'),
    'kangra': ('Kangra', 'Himachal Pradesh'),
    'una': ('Una', 'Himachal Pradesh'),
    'kullu': ('Kullu', 'Himachal Pradesh'),
    'bilaspur hp': ('Bilaspur', 'Himachal Pradesh'),
    'parwanoo': ('Solan', 'Himachal Pradesh'),
    
    # West Bengal
    'kolkata': ('Kolkata', 'West Bengal'),
    'calcutta': ('Kolkata', 'West Bengal'),
    'purulia': ('Purulia', 'West Bengal'),
    'darjeeling': ('Darjeeling', 'West Bengal'),
    'burdwan': ('Burdwan', 'West Bengal'),
    'asansol': ('Asansol', 'West Bengal'),
    'haldia': ('Haldia', 'West Bengal'),
    'birbhum': ('Birbhum', 'West Bengal'),
    'midnapore': ('Midnapore', 'West Bengal'),
    'bankura': ('Bankura', 'West Bengal'),
    'kharagpur': ('Kharagpur', 'West Bengal'),
    'howrah': ('Howrah', 'West Bengal'),
    'raniganj': ('Burdwan', 'West Bengal'),
    
    # Bihar
    'patna': ('Patna', 'Bihar'),
    'rohtas': ('Rohtas', 'Bihar'),
    'buxar': ('Buxar', 'Bihar'),
    'munger': ('Munger', 'Bihar'),
    'west champaran': ('West Champaran', 'Bihar'),
    'khagaria': ('Khagaria', 'Bihar'),
    'madhubani': ('Madhubani', 'Bihar'),
    'siwan': ('Siwan', 'Bihar'),
    'gopalganj': ('Gopalganj', 'Bihar'),
    'muzaffarpur': ('Muzaffarpur', 'Bihar'),
    'darbhanga': ('Darbhanga', 'Bihar'),
    'bhagalpur': ('Bhagalpur', 'Bihar'),
    'samastipur': ('Samastipur', 'Bihar'),
    'begusarai': ('Begusarai', 'Bihar'),
    'sitamarhi': ('Sitamarhi', 'Bihar'),
    'gaya': ('Gaya', 'Bihar'),
    'jehanabad': ('Jehanabad', 'Bihar'),
    'nalanda': ('Nalanda', 'Bihar'),
    'sheikhpura': ('Sheikhpura', 'Bihar'),
    'barauni': ('Begusarai', 'Bihar'),
    'sasaram': ('Rohtas', 'Bihar'),
    
    # Maharashtra
    'mumbai': ('Mumbai', 'Maharashtra'),
    'pune': ('Pune', 'Maharashtra'),
    'nagpur': ('Nagpur', 'Maharashtra'),
    'aurangabad mh': ('Aurangabad', 'Maharashtra'),
    'aurangabad': ('Aurangabad', 'Maharashtra'), 
    'kalyan': ('Kalyan', 'Maharashtra'),
    'borivali': ('Mumbai', 'Maharashtra'),
    'lonavla': ('Pune', 'Maharashtra'),
    'nashik': ('Nashik', 'Maharashtra'),
    'nasik': ('Nashik', 'Maharashtra'),
    'thane': ('Thane', 'Maharashtra'),
    
    # Karnataka
    'bangalore': ('Bengaluru', 'Karnataka'),
    'bengaluru': ('Bengaluru', 'Karnataka'),
    'mysore': ('Musuru', 'Karnataka'),
    'hubli': ('Hubballi', 'Karnataka'),
    'mangalore': ('Mangaluru', 'Karnataka'),
    
    # Tamil Nadu
    'chennai': ('Chennai', 'Tamil Nadu'),
    'coimbatore': ('Coimbatore', 'Tamil Nadu'),
    'madurai': ('Madurai', 'Tamil Nadu'),
    'hosur': ('Hosur', 'Tamil Nadu'),
    
    # Telangana / Andhra Pradesh
    'hyderabad': ('Hyderabad', 'Telangana'),
    'secunderabad': ('Secunderabad', 'Telangana'),
    
    # Kerala
    'kochi': ('Kochi', 'Kerala'),
    'trivandrum': ('Thiruvananthapuram', 'Kerala'),
    'thiruvananthapuram': ('Thiruvananthapuram', 'Kerala'),
    
    # Madhya Pradesh
    'indore': ('Indore', 'Madhya Pradesh'),
    'bhopal': ('Bhopal', 'Madhya Pradesh'),
    'gwalior': ('Gwalior', 'Madhya Pradesh'),
    'jabalpur': ('Jabalpur', 'Madhya Pradesh'),
    'barwani mp': ('Barwani', 'Madhya Pradesh'),
    
    # Jammu & Kashmir
    'jammu': ('Jammu', 'Jammu & Kashmir'),
    'srinagar': ('Srinagar', 'Jammu & Kashmir'),
}

SCHOOLS_DB = {
    'dps ballabgarh': ('Ballabgarh', 'Haryana'),
    'heritage noida': ('Noida', 'Uttar Pradesh'),
    'vvdav vikaspuri': ('New Delhi', 'Delhi'),
    'banasthali public school vikaspuri': ('New Delhi', 'Delhi'),
    'sarvottam international school gn': ('Greater Noida', 'Uttar Pradesh'),
    'sarvottam international school': ('Greater Noida', 'Uttar Pradesh'),
    'dlf school ghaziabad': ('Ghaziabad', 'Uttar Pradesh'),
    'sharanalaya world school': ('Chennai', 'Tamil Nadu'),
    'gd goenka global school noida': ('Noida', 'Uttar Pradesh'),
    'gd goenka sec - 48': ('Gurugram', 'Haryana'),
    'gd goenka sec 48': ('Gurugram', 'Haryana'),
    'gdgoenka sec 48': ('Gurugram', 'Haryana'),
    'odm international school': ('Bhubaneswar', 'Odisha'),
    'sapphire international school cr': ('New Delhi', 'Delhi'),
    'gdgps sirsa': ('Sirsa', 'Haryana'),
    'gd goenka school sitapur': ('Sitapur', 'Uttar Pradesh'),
    'gdgoenka rewari': ('Rewari', 'Haryana'),
    'gd goenka public school': ('New Delhi', 'Delhi'), 
    'gd goenka aurangabad': ('Aurangabad', 'Maharashtra'),
    'ved vyas dav school vikaspuri': ('New Delhi', 'Delhi'),
    'bal bhawan international school dwarka': ('New Delhi', 'Delhi'),
    'hazzle moon school, bijnor': ('Bijnor', 'Uttar Pradesh'),
    'vgs rohini': ('New Delhi', 'Delhi'),
    'gd goenka jind haryana': ('Jind', 'Haryana'),
    'dps raj nagr': ('Ghaziabad', 'Uttar Pradesh'),
    'dps raj nagar': ('Ghaziabad', 'Uttar Pradesh'),
    'mussoorie international school': ('Mussoorie', 'Uttarakhand'),
    'okabridge intl school': ('Kolkata', 'West Bengal'),
    'mody institute of education & research': ('Lakshmangarh', 'Rajasthan'),
    'mody institute of education and research': ('Lakshmangarh', 'Rajasthan'),
    'hopetown girls school': ('Dehradun', 'Uttarakhand'),
    'hopetown school': ('Dehradun', 'Uttarakhand'),
    'ecole global school': ('Dehradun', 'Uttarakhand'),
    'dyal singh public school': ('Karnal', 'Haryana'),
    'dr pillai global academy, mumbai': ('Mumbai', 'Maharashtra'),
    'dr pillai global academy': ('Mumbai', 'Maharashtra'),
    'dps vidyut nagar': ('Dadri', 'Uttar Pradesh'),
    'dps east bangalore': ('Bengaluru', 'Karnataka'),
    'bliss international school': ('Pune', 'Maharashtra'), 
    'yadavindra public school mohali': ('Mohali', 'Punjab'),
    'welham girls school': ('Dehradun', 'Uttarakhand'),
    'bps pilani': ('Pilani', 'Rajasthan'),
    'birla public school': ('Pilani', 'Rajasthan'),
    'vidya niketan school': ('Bengaluru', 'Karnataka'), 
    'vidsan charterhouse': ('Faridabad', 'Haryana'),
    'vibgyor school pune': ('Pune', 'Maharashtra'),
    'universal high school': ('Mumbai', 'Maharashtra'),
    'trivandrum international school': ('Thiruvananthapuram', 'Kerala'),
    'the vikasa school': ('Tuticorin', 'Tamil Nadu'),
    'shishukunj international school': ('Indore', 'Madhya Pradesh'),
    'the sankaar valley school': ('Bhopal', 'Madhya Pradesh'),
    'the mann school': ('New Delhi', 'Delhi'),
    'the lawrence school': ('Lovedale', 'Tamil Nadu'), 
    'hyderabad public school': ('Hyderabad', 'Telangana'),
    'matrikiran school': ('Gurugram', 'Haryana'),
    'shree sarasswathi vidhyaah': ('Mettupalayam', 'Tamil Nadu'),
    'cathedral and john connon school': ('Mumbai', 'Maharashtra'),
    'assam valley school': ('Balipara', 'Assam'),
    'bbps vishalahapatnam': ('Visakhapatnam', 'Andhra Pradesh'),
    'indus bangalore': ('Bengaluru', 'Karnataka'),
    'st michael\'s school': ('Siliguri', 'West Bengal'),
    'sri kumaran children s home': ('Bengaluru', 'Karnataka'),
    'sparsh global school': ('Greater Noida', 'Uttar Pradesh'),
    'silver oaks international school': ('Hyderabad', 'Telangana'),
    'sharnbasveshwar residential': ('Kalaburagi', 'Karnataka'),
    'selaqui international school': ('Dehradun', 'Uttarakhand'),
    'scindia international school': ('Gwalior', 'Madhya Pradesh'),
    'sarala birla academy': ('Bengaluru', 'Karnataka'),
    'sanjay ghodawat international': ('Kolhapur', 'Maharashtra'),
    'sancta maria international school': ('Hyderabad', 'Telangana'),
    'sainik school': ('Korukonda', 'Andhra Pradesh'), 
    'sage international school': ('Bhopal', 'Madhya Pradesh'),
    'rustomjee cambridge international': ('Mumbai', 'Maharashtra'),
    'rashtirya indian military college': ('Dehradun', 'Uttarakhand'),
    'rajmata krishna kumari girls': ('Jodhpur', 'Rajasthan'),
    'pravara public school': ('Ahmednagar', 'Maharashtra'),
    'pinegrove school': ('Dharampur', 'Himachal Pradesh'),
    'palladium school': ('Hisar', 'Haryana'),
    'oberoi international school': ('Mumbai', 'Maharashtra'),
    'new digamber public school': ('Indore', 'Madhya Pradesh'),
    'neerja modi school': ('Jaipur', 'Rajasthan'),
    'mahindra united world college': ('Pune', 'Maharashtra'),
    'maa anandmayee memorial school': ('Haridwar', 'Uttarakhand'),
    'laidlow memorial': ('Ketti', 'Tamil Nadu'),
    'lk singhania education centre': ('Gotan', 'Rajasthan'),
    'keystone international sschool': ('Ooty', 'Tamil Nadu'),
    'kanakia international school': ('Mumbai', 'Maharashtra'),
    'jindal vidya mandir': ('Vasind', 'Maharashtra'),
    
    # Additional common unresolved schools
    'shri guru ram rai': ('Dehradun', 'Uttarakhand'),
    'sgrr': ('Dehradun', 'Uttarakhand'),
    'sawai man singh': ('Jaipur', 'Rajasthan'),
    'jayshree periwal': ('Jaipur', 'Rajasthan'),
    'rawat public': ('Jaipur', 'Rajasthan'),
    'maharaja sawai': ('Jaipur', 'Rajasthan'),
    'gyan ashram': ('Jaipur', 'Rajasthan'),
    'm s s public': ('Jaipur', 'Rajasthan'),
    'all best childrens': ('Jaipur', 'Rajasthan'),
    'step ahead': ('Jaipur', 'Rajasthan'),
    'indo bharat': ('Jaipur', 'Rajasthan'),
    'shri radhaswami': ('Jaipur', 'Rajasthan'),
    'brightland girls': ('Jaipur', 'Rajasthan'),
    'yugantar': ('Jaipur', 'Rajasthan'),
    'apex international': ('Jaipur', 'Rajasthan'),
    'aurobindo': ('Jaipur', 'Rajasthan'),
    'universe public': ('Jaipur', 'Rajasthan'),
    'vadanta': ('Jaipur', 'Rajasthan'),
    'discovery': ('Jaipur', 'Rajasthan'),
    'petals': ('Jaipur', 'Rajasthan'),
    'j. d. international': ('Jaipur', 'Rajasthan'),
    'mahapragya': ('Jaipur', 'Rajasthan'),
    'nims': ('Jaipur', 'Rajasthan'),
    'vinayak': ('Jaipur', 'Rajasthan'),
    'the rajasthan school': ('Jaipur', 'Rajasthan'),
    's r n': ('Jaipur', 'Rajasthan'),
    'g r global': ('Jaipur', 'Rajasthan'),
    'st. anselm': ('Jaipur', 'Rajasthan'),
    'care international': ('Tiruchirappalli', 'Tamil Nadu'),
    'crescent public school': ('Jaipur', 'Rajasthan'),
    
    # Specific Delhi/NCR DAV alignment
    'darbari lal dav': ('New Delhi', 'Delhi'),
    'jhabbhan lal dav': ('New Delhi', 'Delhi'),
    'hans raj model': ('New Delhi', 'Delhi'),
    'arvind gupta dav': ('New Delhi', 'Delhi'),
    'shaheed rajpal dav': ('New Delhi', 'Delhi'),
    'sls d.a.v': ('New Delhi', 'Delhi'),
    'sls dav': ('New Delhi', 'Delhi'),
    'veda vyasa dav': ('New Delhi', 'Delhi'),
    'veda vyasa d.a.v': ('New Delhi', 'Delhi'),
    'm. l. khanna dav': ('New Delhi', 'Delhi'),
    'm. l. khanna d.a.v': ('New Delhi', 'Delhi'),
    'suraj bhan dav': ('New Delhi', 'Delhi'),
    'kulachi hans raj': ('New Delhi', 'Delhi'),
    'saint soldier': ('Jalandhar', 'Punjab'),
    'carmel convent': ('Chandigarh', 'Chandigarh'),
    'manav mangal': ('Chandigarh', 'Chandigarh'),
    'springfield': ('Ambala', 'Haryana'),
}

STATE_RULES = [
    (re.compile(r'\bharyana\b'), 'Haryana'),
    (re.compile(r'\bpunjab\b|\bpb\b'), 'Punjab'),
    (re.compile(r'\buttar\s+pradesh\b|\bup\b'), 'Uttar Pradesh'),
    (re.compile(r'\brajasthan\b|\braj\b'), 'Rajasthan'),
    (re.compile(r'\bdelhi\b|\bnd\b|\bdl\b'), 'Delhi'),
    (re.compile(r'\bhimachal\b|\bhp\b'), 'Himachal Pradesh'),
    (re.compile(r'\buttarakhand\b|\buk\b|\buttaranchal\b'), 'Uttarakhand'),
    (re.compile(r'\bchhattisgarh\b|\bcg\b'), 'Chhattisgarh'),
    (re.compile(r'\bwest\s+bengal\b|\bwb\b'), 'West Bengal'),
    (re.compile(r'\bbihar\b'), 'Bihar'),
    (re.compile(r'\bmaharashtra\b|\bmh\b'), 'Maharashtra'),
    (re.compile(r'\bmadhya\s+pradesh\b|\bmp\b'), 'Madhya Pradesh'),
    (re.compile(r'\btamil\s+nadu\b|\btn\b'), 'Tamil Nadu'),
    (re.compile(r'\bjammu\b|\bj&k\b'), 'Jammu & Kashmir'),
    (re.compile(r'\bkarnataka\b'), 'Karnataka'),
    (re.compile(r'\bkerala\b'), 'Kerala'),
    (re.compile(r'\bodisha\b|\borissa\b'), 'Odisha'),
    (re.compile(r'\btelangana\b'), 'Telangana'),
    (re.compile(r'\bandhra\s+pradesh\b|\bap\b'), 'Andhra Pradesh'),
    (re.compile(r'\bassam\b'), 'Assam'),
]

# Indian Mobile Prefix Map to State
PHONE_PREFIX_MAP = {
    '9419': ('', 'Jammu & Kashmir'),
    '7006': ('', 'Jammu & Kashmir'),
    '9814': ('', 'Punjab'),
    '9815': ('', 'Punjab'),
    '9417': ('', 'Punjab'),
    '7973': ('', 'Punjab'),
    '8146': ('', 'Punjab'),
    '8195': ('', 'Punjab'),
    '9871': ('', 'Delhi'),
    '9540': ('', 'Delhi'),
    '9310': ('', 'Delhi'),
    '9810': ('', 'Delhi'),
    '9313': ('', 'Delhi'),
    '9910': ('', 'Delhi'),
    '9873': ('', 'Delhi'),
    '9650': ('', 'Delhi'),
    '9818': ('', 'Delhi'),
    '9868': ('', 'Delhi'),
    '9911': ('', 'Delhi'),
    '9560': ('', 'Delhi'),
    '9718': ('', 'Delhi'),
    '9667': ('', 'Delhi'),
    '9999': ('', 'Delhi'),
    '8587': ('', 'Delhi'),
    '8860': ('', 'Delhi'),
    '9811': ('', 'Delhi'),
    '8700': ('', 'Delhi'),
    '7082': ('', 'Haryana'),
    '8053': ('', 'Haryana'),
    '8222': ('', 'Haryana'),
    '8814': ('', 'Haryana'),
    '7633': ('', 'Bihar'),
    '9934': ('', 'Bihar'),
    '7351': ('', 'Uttar Pradesh'),
    '9634': ('', 'Uttar Pradesh'),
    '9927': ('', 'Uttar Pradesh'),
    '9411': ('', 'Uttar Pradesh'),
    '9756': ('', 'Uttar Pradesh'),
    '8192': ('', 'Uttar Pradesh'),
    '8369': ('', 'Maharashtra'),
    '9029': ('', 'Maharashtra'),
    '9892': ('', 'Maharashtra'),
    '9920': ('', 'Maharashtra'),
    '9673': ('', 'Maharashtra'),
    '9011': ('', 'Maharashtra'),
    '9764': ('', 'Maharashtra'),
    '9003': ('', 'Tamil Nadu'),
    '6369': ('', 'Tamil Nadu'),
    '9965': ('', 'Tamil Nadu'),
    '9442': ('', 'Tamil Nadu'),
    '9632': ('', 'Karnataka'),
    '9901': ('', 'Karnataka'),
    '9972': ('', 'Karnataka'),
    '9535': ('', 'Karnataka'),
    '9742': ('', 'Karnataka'),
    '7075': ('', 'Andhra Pradesh'),
    '9642': ('', 'Andhra Pradesh'),
    '8008': ('', 'Andhra Pradesh'),
    '9446': ('', 'Kerala'),
    '9926': ('', 'Madhya Pradesh'),
    '8889': ('', 'Madhya Pradesh'),
    '8959': ('', 'Madhya Pradesh'),
    '9826': ('', 'Madhya Pradesh'),
    '9593': ('', 'West Bengal'),
    '9784': ('', 'Rajasthan'),
    '9829': ('', 'Rajasthan'),
    '9587': ('', 'Rajasthan'),
    '9828': ('', 'Rajasthan'),
    '9816': ('', 'Himachal Pradesh'),
    '9957': ('', 'Assam'),
}

def parse_location_local(name):
    """
    Tries to resolve city and state using regex and local dictionaries.
    """
    name_clean = name.strip()
    name_lower = name_clean.lower()
    
    # 1. Exact match in SCHOOLS_DB
    for school_key, loc in SCHOOLS_DB.items():
        if school_key in name_lower:
            return loc
            
    # 2. Check standard prefixes
    if re.match(r'^DL\b', name_clean):
        return 'New Delhi', 'Delhi'
    if re.match(r'^NOIDA\b', name_clean):
        return 'Noida', 'Uttar Pradesh'
    if re.match(r'^GZB\b', name_clean):
        return 'Ghaziabad', 'Uttar Pradesh'
    if re.match(r'^IND\b', name_clean):
        return 'Indirapuram', 'Uttar Pradesh'
        
    # 3. Check cities database
    sorted_cities = sorted(CITIES_MAP.keys(), key=len, reverse=True)
    for city_kw in sorted_cities:
        if re.search(r'\b' + re.escape(city_kw) + r'\b', name_lower):
            if city_kw == 'aurangabad' and 'bihar' in name_lower:
                return 'Aurangabad', 'Bihar'
            return CITIES_MAP[city_kw]
            
    # 4. Check state rules
    for pattern, state in STATE_RULES:
        if pattern.search(name_lower):
            return '', state
            
    return '', ''

def parse_location_by_phone(phone):
    """
    Tries to lookup the Circle/State using the first 4 digits of the Indian mobile number.
    """
    phone_clean = re.sub(r'\D', '', str(phone))
    if len(phone_clean) >= 4:
        prefix = phone_clean[:4]
        if prefix in PHONE_PREFIX_MAP:
            return PHONE_PREFIX_MAP[prefix]
    return '', ''
